### ISSUE TITLE
Arbendium/ESLint in WebStorm don't work

### ISSUE THREAD

**Issue by AndreiSoroka** [arbendium/eslint-config#1]
### Error:
<img width="1103" alt="image" src="https://github.com/arbendium/eslint-config/assets/6079139/67590fee-77b7-4870-9330-0d378d7e9090">

```
TypeError: (intermediate value).resolve is not a function

TypeError: (intermediate value).resolve is not a function
    at file:///Users/andreisoroka/git/arbendium/video-srs/node_modules/@arbendium/eslint-config/index.js:5:50
Process finished with exit code -1
```

<img width="796" alt="image" src="https://github.com/arbendium/eslint-config-base/assets/6079139/6bdc8a52-6b48-49e2-9bf0-cf8cd644cfa0">

### Details
WebStorm 2023.3 EAP
Build #WS-233.10527.23, built on October 23, 2023

node v18.18.2

**Comment by keijokapp** [comment]
We only support the latest NodeJS version.
